services:
  virtualled:
    image: virtualled
    build:
      context: .
      dockerfile: ./VirtualLED/Dockerfile
    ports:
      - 80:8080
      - 443:8081
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - AuthorizedUser=${AuthorizedUser}
      - AuthorizedUserPassword=${AuthorizedUserPassword}
