services:
  virtualled:
    image: virtualled
    build:
      context: .
      dockerfile: ./src/VirtualLED/Dockerfile
    ports:
      - 8080:8080
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - AuthorizedUser=${AuthorizedUser}
      - AuthorizedUserPassword=${AuthorizedUserPassword}
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - ASPNETCORE_FORWARDEDHEADERS_ENABLED=true
